### PR TITLE
Formatter, linter, 

### PR DESCRIPTION
**Pull request by foxyseta**
CI/CD requires adding a TOKEN secret with no permissions.

### CODE REVIEW

**Comment by lucat1** [comment]
Just use `GITHUB_TOKEN` which is provided by default

**Comment by foxyseta** [comment]
Oh that's why GITHUB wouldn't let me create a custom "GITHUB_TOKEN" variable as in the original yml lol

**Review by lucat1 — APPROVED** [review]
LGTM

**Comment by foxyseta** [comment]
Fixed!

**Pull request merged**
