### PR TITLE
Rainbow layer

### LINKED ISSUE #74: Rainbow delimiters via Treesitter
Plugin:

https://gitlab.com/HiPhish/rainbow-delimiters.nvim

Only so many languages are supported:

https://gitlab.com/HiPhish/rainbow-delimiters.nvim/-/tree/master/queries?ref_type=heads

Should such a layer be called "delimiters"? "Rainbow"? Should it be enabled by default?

### PR DESCRIPTION
**Pull request by foxyseta**
Closes #74

### CODE REVIEW

**Comment by lucat1** [comment]
Needs rebasing on main before the review

**Comment by foxyseta** [comment]
@lucat1 rebased.

**Review by lucat1 — CHANGES_REQUESTED** [review]
I don't like the fact that you have to configure the layer via global vars. I would avoid it if possible (and I think that is the case here). We can accept a config for the layer, then iterate over the dictionary recursively and set the keys in the dictionary in the global variable space.

**Review by lucat1 — APPROVED** [review]
LGTM

**Pull request merged**
